import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate as integral
from scipy.linalg import lstsq

def EXP(x):
    return np.exp(x)
def coscos(x):
    return (np.cos(np.cos(x)))

x = np.arange(-2*np.pi,4*np.pi,0.1)
y1 = EXP(x)
z=coscos(x)

plt.figure(0)
plt.semilogy(x,y1)
plt.xlabel('$x$')
plt.ylabel('$exp(x)$')
plt.title('Semilog plot for exp(x)')
plt.grid(True)
plt.show()

plt.figure(1)
plt.plot(x,z)
plt.xlabel('$x$')
plt.ylabel('$cos(cos(x))$')
plt.title('Plot for cos(cos((x)))')
plt.grid(True)
plt.show()

def cosm(x,k,f):
    return np.cos(k*x)*f(x)
def sinm(x,k,f):
    return np.sin(k*x)*f(x)
exp_a0=(integral.quad(cosm,0,2*np.pi,args=(0,EXP))[0])/(2*np.pi)
exp_an=np.array([integral.quad(cosm,0,2*np.pi,args=(k,EXP))[0] for k in range(1,26)])/(np.pi)
exp_bn=np.array([integral.quad(sinm,0,2*np.pi,args=(k,EXP))[0] for k in range(1,26)])/(np.pi)

coscos_a0=(integral.quad(cosm,0,2*np.pi,args=(0,coscos))[0])/(2*np.pi)
coscos_an=np.array([integral.quad(cosm,0,2*np.pi,args=(k,coscos))[0] for k in range(1,26)])/(np.pi)
coscos_bn=np.array([integral.quad(sinm,0,2*np.pi,args=(k,coscos))[0] for k in range(1,26)])/(np.pi)

exp_coeff=[exp_a0]
exp_coeff[1:26]=exp_an
exp_coeff[26:52]=exp_bn

coscos_coeff=[coscos_a0]
coscos_coeff[1:26]=coscos_an
coscos_coeff[26:52]=coscos_bn

plt.figure(2)
plt.subplot(211)
plt.semilogy(list(range(26)),np.array(exp_coeff[:26]),'ro')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Semilog plot for Cos coefficients of exp(x)')
plt.grid(True)
plt.subplot(212)
plt.semilogy(list(range(1,26)),np.array(np.abs(exp_coeff[26:])),'ro')
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Semilog plot for Sin coefficients of exp(x)')
plt.grid(True)
plt.show()

plt.figure(3)
plt.subplot(211)
plt.loglog(list(range(26)),np.array(exp_coeff[:26]),'ro')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Loglog plot for Cos coefficients of exp(x)')
plt.grid(True)
plt.subplot(212)
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Loglog plot for Sin coefficients of exp(x)')
plt.loglog(list(range(1,26)),np.array(np.abs(exp_coeff[26:])),'ro')
plt.grid(True)
plt.show()

plt.figure(4)
plt.subplot(211)
plt.semilogy(list(range(26)),np.array(coscos_coeff[:26]),'ro')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Semilog plot for Cos coefficients of cos(cos((x)))')
plt.grid(True)
plt.subplot(212)
plt.semilogy(list(range(1,26)),np.array(np.abs(coscos_coeff[26:])),'ro')
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Semilog plot for Sin coefficients of cos(cos((x)))')
plt.grid(True)
plt.show()

plt.figure(5)
plt.subplot(211)
plt.loglog(list(range(26)),np.array(coscos_coeff[:26]),'ro')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Loglog plot for Cos coefficients of cos(cos((x)))')
plt.grid(True)
plt.subplot(212)
plt.loglog(list(range(1,26)),np.array(np.abs(coscos_coeff[26:])),'ro')
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Loglog plot for Sin coefficients of cos(cos((x)))')
plt.grid(True)
plt.show()

y=np.linspace(0,2*np.pi,401)
y=y[:-1]
b_exp=EXP(y)
b_coscos=coscos(y)
A=np.zeros((400,51))
A[:,0]=1
for k in range(1,26):
    A[:,k]=np.cos(k*y)
    A[:,k+25]=np.sin(k*y)

c1=lstsq(A,b_exp)[0]
c2=lstsq(A,b_coscos)[0]

#np.set_printoptions(formatter={'float_kind':'{:f}'.format})
plt.figure(2)
plt.subplot(211)
plt.semilogy(list(range(26)),np.array(exp_coeff[:26]),'ro',label='obtained by integral')
plt.semilogy(list(range(26)),np.array(np.abs(c1[:26])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Semilog plot for Cos coefficients of exp(x)')
plt.legend()
plt.grid(True)
plt.subplot(212)
plt.semilogy(list(range(1,26)),np.array(np.abs(exp_coeff[26:])),'ro',label='obtained by integral')
plt.semilogy(list(range(1,26)),np.array(np.abs(c1[26:])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Semilog plot for Sin coefficients of exp(x)')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(3)
plt.subplot(211)
plt.loglog(list(range(26)),np.array(exp_coeff[:26]),'ro',label='obtained by integral')
plt.loglog(list(range(26)),np.array(np.abs(c1[:26])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Loglog plot for Cos coefficients of exp(x)')
plt.legend()
plt.grid(True)
plt.subplot(212)
plt.loglog(list(range(1,26)),np.array(np.abs(exp_coeff[26:])),'ro',label='obtained by integral')
plt.loglog(list(range(1,26)),np.array(np.abs(c1[26:])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Loglog plot for Sin coefficients of exp(x)')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(4)
plt.subplot(211)
plt.semilogy(list(range(26)),np.array(coscos_coeff[:26]),'ro',label='obtained by integral')
plt.semilogy(list(range(26)),np.array(np.abs(c2[:26])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Semilog plot for Cos coefficients of cos(cos((x)))')
plt.legend()
plt.grid(True)
plt.subplot(212)
plt.semilogy(list(range(1,26)),np.array(np.abs(coscos_coeff[26:])),'ro',label='obtained by integral')
plt.semilogy(list(range(1,26)),np.array(np.abs(c2[26:])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Semilog plot for Sin coefficients of cos(cos((x)))')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(5)
plt.subplot(211)
plt.loglog(list(range(26)),np.array(coscos_coeff[:26]),'ro',label='obtained by integral')
plt.loglog(list(range(26)),np.array(np.abs(c2[:26])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$a_n$')
plt.title('Loglog plot for Cos coefficients of cos(cos((x)))')
plt.legend()
plt.grid(True)
plt.subplot(212)
plt.loglog(list(range(1,26)),np.array(np.abs(coscos_coeff[26:])),'ro',label='obtained by integral')
plt.loglog(list(range(1,26)),np.array(np.abs(c2[26:])),'go',label='obtained by lstsq')
plt.xlabel('$n$')
plt.ylabel('$b_n$')
plt.title('Loglog plot for Sin coefficients of cos(cos((x)))')
plt.legend()
plt.grid(True)
plt.show()

print("Maximum deviation in case of exp(x) is", np.amax(np.abs(c1-np.asarray(exp_coeff))))

print("Maximum deviation in case of cos(cos(x)) is",np.amax(np.abs(c2-np.asarray(coscos_coeff))))


b_est_exp=np.dot(A,c1)
b_est_coscos=np.dot(A,c2)

y1 = EXP(y)
z=coscos(y)

plt.figure(0)
plt.semilogy(y,y1,label='Original')
plt.semilogy(y,b_est_exp,'ro',label='Obtained')
plt.xlabel('$x$')
plt.ylabel('$exp(x)$')
plt.title('Semilog plot for exp(x)')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(1)
plt.plot(y,b_est_coscos,'ro',label='Obtained')
plt.plot(y,z,label='Original')
plt.xlabel('$x$')
plt.ylabel('$cos(cos(x))$')
plt.title('Plot for cos(cos((x)))')
plt.legend()
plt.grid(True)
plt.show()
